---
title: "Tidy Tuesday - Spam"
author: "Alison Bautista"
date: "2023-08-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggtext)
library(showtext)
library(tidytext)
library(data.table)
library(paletteer)
library(extrafont)
library(RColorBrewer)
library(cowplot)
library(magick)
library(usethis)
```

```{r}
#load the data in
tuesdata <- tidytuesdayR::tt_load(2023, week = 33)

#selecting dataset from database
spam <- tuesdata$spam

#show data
spam

```
```{r}
#remove the first column because capitalize letter string
spam <- spam[,-1]


#delimit file so variables are in one column
spam_data <- melt(spam, id.vars = "yesno", variable.factor = FALSE, value.factor = FALSE)
```



```{r}
#cleaning the data
df <- spam_data %>% 
  filter(value!= 0) %>% 
  group_by(variable, yesno) %>%
  #renaming y/n vairables
  mutate(yesno = case_when(
    yesno == "y" ~ "Spam",
    yesno == "n" ~ "Not Spam"),
    #renaming each variable
    variable = case_when(
      variable == "crl.tot" ~ "Capitalized Letter",
      variable == "dollar" ~"$$",
      variable == "bang" ~ "!!",
      variable == "money" ~ '"money"',
      variable == "n000" ~ '"000"',
      variable == "make" ~ '"make"'
    )) %>% 
  #counting total occurances
  summarise(sum_value = sum(value), count = n()) %>%
  distinct() %>%
  #calculating percentage of occurances and including in df
  mutate(perc_occurances = paste(round((count/sum(count)*100), 0), "%", sep=""),
         count_occurances = paste(count, " emails ", sep = ""),
         perc_emails = sum(count)/ nrow(spam))

df
```




```{r fig.height= 4, fig.width= 6}
#creating spam plot
spam_plot <- df %>%
  #setting graph variables and reordering bars
  ggplot(aes(x = count, y = reorder(variable, -count), fill = yesno)) + 
  geom_col(color = 'grey', width = .8) +
  # color selection of bars
  scale_fill_manual(values=c('midnightblue', 'rosybrown2')) +
  #creating percentage label in bars
  geom_text(aes(group = yesno, 
                label = (ifelse(yesno == "Spam", perc_occurances, ""))),
                hjust = 1.4, 
                nudge_x = -2,
                size = 2, 
                fontface = "bold") + 
  #title and other text elemtnts
  labs(title = "<span style='font-size:16pt'>you've got...</span>
       <span style='font-size:38pt'>SPAM</span>",
       subtitle = "Occurrences of '000', 'money', 'make', '$', '!' and how frequently\nthey trigger spam filters,shown across 4,600 emails.",
       caption = "Source: Vincent Arel-Bundock's Rdatasets- Spam Emails | Data Viz by Alison Bautista") +
  xlab("Total Number of emails") +
  ylab("") +
  #resetting graph sitze and setting theme
  theme(aspect.ratio = 1/3,
        panel.background = element_rect(fill = 'midnightblue'),
        panel.grid.major = element_line(color = 'midnightblue'),
        panel.grid.minor = element_line(color = 'midnightblue'),
        plot.background = element_rect(fill = 'midnightblue'),
        legend.background = element_rect(fill = 'midnightblue'),
        legend.title = element_blank(),
        legend.text = element_text(color = "grey", size =7),
        plot.title = element_markdown(family = "PT Serif", color = "gold", face = "bold"),
        plot.subtitle = element_text(color = 'grey', size = 8, family = "Spot Mono"),
        plot.caption = element_text(color = 'grey', size = 5, family = "Spot Mono", hjust = 1.5),
        axis.title.x = element_text(color = 'grey', family = "PT Serif"),
        axis.text = element_text(color = 'gold', face = "bold", family = "PT Serif")
        )

spam_plot
```

```{r}
#exporting plot
ggsave(spam_plot, filename = "spam_plot.png", height = 5, width = 7.5)
```


